import { useCallback, useEffect, useState } from 'react';
import { Badge, Button, Icon, Panel, SectionHeader } from '../../components/ui';
import { json } from '../../services/api';
import type { AnyRow } from '../../types';

const dateLabel = (value: unknown) => { if (!value) return '-'; const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? '-' : date.toLocaleDateString('pt-BR'); };
const reasonLabel: Record<string, string> = { active_subscription: 'Assinatura ativa', trialing: 'Periodo de avaliacao', manual_grant: 'Acesso concedido manualmente', no_subscription: 'Sem assinatura ativa', subscription_expired: 'Assinatura expirada', canceled: 'Assinatura cancelada', past_due: 'Pagamento pendente', unpaid: 'Pagamento nao confirmado' };
const featureLabels: Record<string, string> = { schedule_enforcement: 'Agenda e horarios', callbacks: 'Callbacks', privacy_requests: 'Privacidade e compliance', onboarding: 'Onboarding', campaigns: 'Campanhas', decision_engine: 'Motor de decisao', recommendations: 'Recomendacoes', operation_health: 'Saude da operacao', analytics_learning: 'Aprendizado analitico', experiments: 'Experimentos', benchmarks: 'Benchmarks', lead_ingestion_api: 'API de leads', advanced_reports: 'Relatorios avancados' };
const levelLabels: Record<string, string> = { full: 'Completo', basic: 'Basico', read_only: 'Consulta' };
const limitLabels: Record<string, string> = { numbers: 'numeros', leads: 'leads', retention_days: 'dias de retencao', max_concurrent_dialers: 'discadores simultaneos' };
const intervalLabels: Record<string, string> = { month: 'mes', year: 'ano' };
const moneyLabel = (amount: unknown, currency = 'brl') => {
  const value = Number(amount);
  if (!Number.isFinite(value)) return '-';
  return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: currency.toUpperCase() }).format(value / 100);
};
const priceLabel = (price: AnyRow) => `${moneyLabel(price.amount, String(price.currency ?? 'brl'))}/${intervalLabels[String(price.interval)] ?? String(price.interval)}`;
const planPricesLabel = (plan: AnyRow) => (Array.isArray(plan.prices) ? plan.prices : []).map((price: AnyRow) => priceLabel(price)).join(' · ');

function PlanEntitlements({ plan }: { plan: AnyRow }) {
  const features = Object.entries((plan.feature_entitlements ?? {}) as Record<string, unknown>).filter(([, level]) => level !== 'none');
  const limits = Object.entries((plan.limit_entitlements ?? {}) as Record<string, unknown>);
  return <>
    {features.length > 0 && <ul className="billing-feature-list">{features.map(([code, level]) => <li key={code}><span>{featureLabels[code] ?? code}</span><small>{levelLabels[String(level)] ?? String(level)}</small></li>)}</ul>}
    {limits.length > 0 && <p className="billing-limit-list">{limits.map(([code, value]) => `${limitLabels[code] ?? code}: ${Number(value).toLocaleString('pt-BR')}`).join(' · ')}</p>}
  </>;
}

export function BillingPage({ tenantId, isSuperAdmin = false }: { tenantId: string; isSuperAdmin?: boolean }) {
  const [billing, setBilling] = useState<AnyRow | null>(null); const [plans, setPlans] = useState<AnyRow[]>([]); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [desiredSeats, setDesiredSeats] = useState(5); const [seatTarget, setSeatTarget] = useState<number | null>(null);
  const load = useCallback(async () => { setError(''); try { const [nextBilling, nextPlans] = await Promise.all([json(`/api/tenants/${tenantId}/billing`), json(`/api/tenants/${tenantId}/billing/plans`)]); setBilling(nextBilling); setPlans(Array.isArray(nextPlans) ? nextPlans : []); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }, [tenantId]);
  useEffect(() => { void load(); }, [load]);
  const openCheckout = async (planCode: string, interval: 'month' | 'year', includedSeats = 1, maxSeats = 100000) => { setBusy(`${planCode}:${interval}`); setError(''); try { const totalSdrSeats = Math.min(maxSeats, Math.max(includedSeats, desiredSeats)); const result = await json(`/api/tenants/${tenantId}/billing/checkout-session`, { method: 'POST', headers: { 'idempotency-key': `checkout:${tenantId}:${planCode}:${interval}:${Date.now()}` }, body: JSON.stringify({ planCode, interval, totalSdrSeats }) }); if (result.url) window.location.assign(result.url); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(''); } };
  const changeSeats = async () => { const current = Number(billing?.includedSdrs ?? 0) + Number(billing?.purchasedExtraSdrs ?? 0); const target = Math.max(1, Math.floor(Number(seatTarget ?? current))); setBusy('seats'); setError(''); try { const preview = await json(`/api/tenants/${tenantId}/billing/seats/preview`, { method: 'POST', body: JSON.stringify({ totalSdrSeats: target }) }); const confirmed = typeof window === 'undefined' || window.confirm(`Alterar para ${preview.targetTotalSeats} SDRs? A alteração será ${preview.effectiveAt === 'period_end' ? 'agendada para o fim do ciclo' : 'enviada para confirmação de pagamento'}.`); if (!confirmed) return; await json(`/api/tenants/${tenantId}/billing/seats`, { method: 'POST', headers: { 'idempotency-key': `seats:${tenantId}:${target}:${Date.now()}` }, body: JSON.stringify({ totalSdrSeats: target }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(''); } };
  const changePlan = async (planCode: string, interval: 'month' | 'year') => { setBusy(`plan:${planCode}:${interval}`); setError(''); try { const preview = await json(`/api/tenants/${tenantId}/billing/plan-change/preview`, { method: 'POST', body: JSON.stringify({ planCode, interval }) }); const confirmed = typeof window === 'undefined' || window.confirm(`Mudar para ${preview.targetPlanName}? A alteração será ${preview.effectiveAt === 'period_end' ? 'agendada para o fim do ciclo' : 'enviada para confirmação de pagamento'}.`); if (!confirmed) return; await json(`/api/tenants/${tenantId}/billing/plan-change`, { method: 'POST', headers: { 'idempotency-key': `plan:${tenantId}:${planCode}:${interval}:${Date.now()}` }, body: JSON.stringify({ planCode, interval }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(''); } };
  const openPortal = async () => { setBusy('portal'); setError(''); try { const result = await json(`/api/tenants/${tenantId}/billing/portal-session`, { method: 'POST', body: JSON.stringify({ returnUrl: window.location.href }) }); if (result.url) window.location.assign(result.url); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(''); } };
  const reconcile = async () => { setBusy('reconcile'); setError(''); try { await json(`/api/tenants/${tenantId}/billing/reconcile`, { method: 'POST' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(''); } };
  const cancelChange = async (id: string) => { setBusy(`cancel:${id}`); setError(''); try { await json(`/api/tenants/${tenantId}/billing/changes/${id}`, { method: 'DELETE' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(''); } };
  const full = billing?.mode === 'full'; const subscription = billing?.subscription; const currentSeatTotal = Number(billing?.includedSdrs ?? 0) + Number(billing?.purchasedExtraSdrs ?? 0); const seatPrices = plans.flatMap((plan) => Array.isArray(plan.seat_prices) ? plan.seat_prices : []); const seatMonthlyPrice = seatPrices.find((price: AnyRow) => price.interval === 'month'); const seatMonthlyLabel = seatMonthlyPrice ? priceLabel(seatMonthlyPrice) : 'R$ 19,90/mes';
  return <div className="page-content">
    <div className="page-heading"><div><span className="eyebrow">ORGANIZACAO</span><h1>Assinatura e cobranca</h1><p>Gerencie o plano, os recursos e o limite de SDRs.</p></div><Badge tone={full ? 'success' : 'warning'}>{full ? 'Operacao liberada' : 'Somente leitura'}</Badge></div>
    {error && <div className="alert" role="alert"><Icon name="alert" size={16} /><span>{error}</span><button onClick={() => setError('')} aria-label="Fechar erro"><Icon name="close" size={15} /></button></div>}
    <Panel><SectionHeader eyebrow="STATUS ATUAL" title={reasonLabel[billing?.reason] ?? 'Consultando assinatura...'} action={<Button variant="ghost" icon="refresh" onClick={() => void load()} disabled={busy !== ''}>Atualizar</Button>} /><div className="metric-grid"><div className="metric-card"><span>Plano</span><strong>{billing?.planName ?? 'Nenhum plano'}</strong><small>{subscription?.status ? `Status Stripe: ${subscription.status}` : 'Ative um plano para liberar alteracoes.'}</small></div><div className="metric-card"><span>SDRs</span><strong>{billing ? `${billing.usedSdrSeats ?? 0} / ${billing.maxSdrs ?? '-'}` : '-'}</strong><small>{billing?.reservedSdrSeats ?? 0} convites reservados</small></div><div className="metric-card"><span>Acesso ate</span><strong>{dateLabel(billing?.accessUntil)}</strong><small>{billing?.cancelAtPeriodEnd ? 'Cancelamento ao fim do ciclo' : 'Renovacao controlada pelo Stripe'}</small></div></div></Panel>
    {full && <Panel><SectionHeader eyebrow="CAPACIDADE" title="Gerencie seus seats" description={`Seats adicionais custam ${seatMonthlyLabel}. Reducoes respeitam membros ativos e convites pendentes.`} /><label className="field-label" htmlFor="seat-target">Total contratado</label><input id="seat-target" className="input" type="number" min={1} max={Number(billing?.planMaxSdrs ?? billing?.maxSdrs ?? 100000)} value={seatTarget ?? currentSeatTotal} onChange={(event) => setSeatTarget(Math.max(1, Number(event.target.value) || 1))} /><div className="table-actions"><Button disabled={busy !== '' || !subscription} onClick={() => void changeSeats()}>{busy === 'seats' ? 'Calculando...' : 'Atualizar seats'}</Button></div><p className="text-muted">Incluidos no plano: {billing?.includedSdrs ?? 0}; adicionais pagos: {billing?.purchasedExtraSdrs ?? 0}; capacidade paga: {billing?.maxSdrs ?? '-'}; teto comercial: {billing?.planMaxSdrs ?? billing?.maxSdrs ?? '-'}.</p></Panel>}
    {Boolean(billing?.pendingChanges?.length) && <Panel><SectionHeader eyebrow="ALTERACAO PENDENTE" title="Aguardando cobrança" description="O limite só muda após confirmação do Stripe." />{billing?.pendingChanges?.map((change: AnyRow) => <div className="admin-compact-row" key={change.id}><div><strong>{change.change_type === 'plan_change' ? `Plano: ${change.to_plan_code}` : `Seats: ${change.to_seat_quantity}`}</strong><small>{change.status === 'scheduled' ? `Efetiva em ${dateLabel(change.effective_at)}` : 'Confirmando pagamento'}</small></div>{change.status === 'scheduled' && <Button variant="ghost" onClick={() => void cancelChange(change.id)} disabled={busy !== ''}>Cancelar</Button>}</div>)}</Panel>}
    {!full && <Panel><SectionHeader eyebrow="ESCOLHA UM PLANO" title="Reative a operacao" description="Sem pagamento confirmado, os dados continuam disponiveis, mas alteracoes e discagens ficam bloqueadas." /><label className="field-label" htmlFor="desired-sdr-seats">Quantidade inicial de SDRs</label><input id="desired-sdr-seats" className="input" type="number" min={1} max={100000} value={desiredSeats} onChange={(event) => setDesiredSeats(Math.max(1, Number(event.target.value) || 1))} /><div className="resource-grid">{plans.map((plan) => <article className="metric-card" key={plan.code}><span>{plan.display_name ?? plan.code}</span><strong>{plan.included_sdrs ?? 0} SDRs incluidos - ate {plan.max_sdrs}</strong><small>{plan.description ?? 'Plano de operacao ZapLiga'} - seat adicional {seatMonthlyLabel}</small><p className="billing-price-line">{planPricesLabel(plan)}</p><PlanEntitlements plan={plan} /><div className="table-actions">{(plan.prices ?? []).map((price: AnyRow) => <Button key={price.interval} disabled={busy !== ''} onClick={() => void openCheckout(plan.code, price.interval, Number(plan.included_sdrs ?? 1), Number(plan.max_sdrs ?? 1))}>{busy === `${plan.code}:${price.interval}` ? 'Abrindo...' : `Assinar - ${priceLabel(price)}`}</Button>)}</div></article>)}</div>{!plans.length && <p className="text-muted">Nenhum preco foi publicado para este ambiente.</p>}</Panel>}
    {full && <Panel><SectionHeader eyebrow="MUDAR DE PLANO" title="Compare os planos" description="Novos recursos só são liberados após confirmação financeira pelo webhook." /><div className="resource-grid">{plans.filter((plan) => plan.code !== billing?.planCode).map((plan) => <article className="metric-card" key={plan.code}><span>{plan.display_name ?? plan.code}</span><strong>{plan.included_sdrs ?? 0} SDRs incluidos - ate {plan.max_sdrs}</strong><small>{plan.description ?? 'Plano de operacao ZapLiga'}</small><p className="billing-price-line">{planPricesLabel(plan)}</p><PlanEntitlements plan={plan} /><div className="table-actions">{(plan.prices ?? []).map((price: AnyRow) => <Button key={price.interval} disabled={busy !== ''} onClick={() => void changePlan(plan.code, price.interval)}>{busy === `plan:${plan.code}:${price.interval}` ? 'Calculando...' : `Mudar - ${priceLabel(price)}`}</Button>)}</div></article>)}</div></Panel>}
    {subscription && <Panel><SectionHeader eyebrow="GERENCIAMENTO" title="Dados de pagamento" description="Atualize cartao, endereco e assinatura pelo portal seguro do Stripe." action={<Button onClick={() => void openPortal()} disabled={busy !== ''}>{busy === 'portal' ? 'Abrindo...' : 'Abrir portal Stripe'}</Button>} />{isSuperAdmin && <div className="table-actions"><Button variant="ghost" icon="refresh" onClick={() => void reconcile()} disabled={busy !== ''}>{busy === 'reconcile' ? 'Sincronizando...' : 'Sincronizar agora'}</Button></div>}</Panel>}
  </div>;
}
