import { useCallback, useEffect, useRef, useState } from 'react';
import type React from 'react';
import { AudioBridge } from '../audio/AudioBridge';
import { apiBaseUrl, json, wsUrl } from '../services/api';
import type { AnyRow, TabKey } from '../types';
import { Badge, Button, Icon } from '../components/ui';
import { Dashboard } from '../features/dashboard/Dashboard';
import { NumbersPage } from '../features/numbers/NumbersPage';
import { LeadsPage } from '../features/leads/LeadsPage';
import { SdrsPage } from '../features/sdrs/SdrsPage';
import { CallsPage } from '../features/calls/CallsPage';
export default function App() {
  const [status, setStatus] = useState<AnyRow>({}); const [numbers, setNumbers] = useState<AnyRow[]>([]); const [leads, setLeads] = useState<AnyRow[]>([]); const [sdrs, setSdrs] = useState<AnyRow[]>([]); const [calls, setCalls] = useState<AnyRow[]>([]); const [logs, setLogs] = useState<AnyRow[]>([]); const [tab, setTab] = useState<TabKey>('dashboard'); const [error, setError] = useState('');
  const [importResult, setImportResult] = useState('');
  const [qr, setQr] = useState<any>(null); const [qrNumberId, setQrNumberId] = useState(''); const [numberForm, setNumberForm] = useState({ label: '', phone: '' }); const [leadForm, setLeadForm] = useState({ name: '', phone: '' }); const [sdrName, setSdrName] = useState(''); const [selectedSdr, setSelectedSdr] = useState(''); const [available, setAvailable] = useState(false); const [connected, setConnected] = useState(false); const [sdrReady, setSdrReady] = useState(false); const [activeCall, setActiveCall] = useState<AnyRow | null>(null); const [qrLoading, setQrLoading] = useState(false); const [showTrialBanner, setShowTrialBanner] = useState(true); const qrBusy = useRef(false); const control = useRef<WebSocket>(); const audio = useRef(new AudioBridge());
  const load = useCallback(async () => { try { const [s, n, l, d, c, events] = await Promise.all([json('/api/dialer/status'), json('/api/numbers'), json('/api/leads'), json('/api/sdrs'), json('/api/calls'), json('/api/dialer/logs')]); setStatus(s); setNumbers(n); setLeads(l); setSdrs(d); setCalls(c); setLogs(events); setError(''); } catch (e) { setError(e instanceof TypeError ? 'API temporariamente indisponível. Tentando reconectar...' : String(e)); } }, []);
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 3000); return () => clearInterval(timer); }, [load]);
  useEffect(() => { if (!qrNumberId) return; let closed = false; const refresh = async () => { if (qrBusy.current) return; qrBusy.current = true; try { const next = await json(`/api/numbers/${qrNumberId}/qr`); if (!closed) setQr(next); } catch { /* mantém o último QR válido */ } finally { qrBusy.current = false; } }; const timer = setInterval(() => void refresh(), 15000); return () => { closed = true; clearInterval(timer); }; }, [qrNumberId]);
  const disconnect = () => { setAvailable(false); setConnected(false); setSdrReady(false); void audio.current.stop(); control.current?.close(); control.current = undefined; };
  const audioCall = useRef('');
  const startAudio = (socket: WebSocket, callId: string) => { if (audioCall.current === callId) return; audioCall.current = callId; void audio.current.start(socket).catch((e) => { const message = e instanceof Error ? e.message : String(e); setError(`Áudio do SDR: ${message}`); if (socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type: 'outcome', callId, outcome: `audio_error:${message.slice(0, 120)}` })); }); };
  const connectSdr = async () => { setError(''); if (!selectedSdr) return setError('Selecione ou cadastre um SDR'); const sdr = sdrs.find((item) => item.id === selectedSdr); if (!sdr) return; disconnect(); const socket = new WebSocket(`${wsUrl()}/ws/sdr`); control.current = socket; socket.binaryType = 'arraybuffer'; socket.onopen = () => { setConnected(true); socket.send(JSON.stringify({ type: 'identify', name: sdr.name })); }; socket.onmessage = (event) => { if (typeof event.data !== 'string') { audio.current.play(event.data); return; } const message = JSON.parse(event.data); if (message.type === 'identified') setSdrReady(true); if (message.type === 'dialer_log') setLogs((current) => [message.log, ...current].slice(0, 100)); if (message.type === 'call_started' && message.lead?.name) { setActiveCall(message); startAudio(socket, message.callId); } if (message.type === 'media_open') { setActiveCall((current) => current ? { ...current, mediaOpen: true } : current); startAudio(socket, message.callId); } if (message.type === 'call_finished') { if (audioCall.current === message.callId) audioCall.current = ''; setActiveCall(null); void audio.current.stop(); void load(); } if (message.type === 'media_active') setActiveCall((current) => current ? { ...current, mediaActive: true } : current); if (message.type === 'error') setError(message.message); }; socket.onclose = () => { audioCall.current = ''; setAvailable(false); setConnected(false); setSdrReady(false); void audio.current.stop(); setActiveCall(null); }; };
  const setAvailability = async (value: boolean) => { if (!connected || !sdrReady || control.current?.readyState !== WebSocket.OPEN) return; if (value) { try { await audio.current.prepare(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); return; } } else { await audio.current.stop(); } setAvailable(value); control.current?.send(JSON.stringify({ type: 'availability', available: value })); };
  const hangup = () => { if (activeCall) control.current?.send(JSON.stringify({ type: 'outcome', callId: activeCall.callId, outcome: 'sdr_hangup' })); void audio.current.stop(); setActiveCall(null); };
  const createNumber = async (event: React.FormEvent) => { event.preventDefault(); try { await json('/api/numbers', { method: 'POST', body: JSON.stringify(numberForm) }); setNumberForm({ label: '', phone: '' }); await load(); } catch (e) { setError(String(e)); } };
  const createLead = async (event: React.FormEvent) => { event.preventDefault(); try { await json('/api/leads', { method: 'POST', body: JSON.stringify(leadForm) }); setLeadForm({ name: '', phone: '' }); await load(); } catch (e) { setError(String(e)); } };
  const createSdr = async (event: React.FormEvent) => { event.preventDefault(); try { await json('/api/sdrs', { method: 'POST', body: JSON.stringify({ name: sdrName }) }); setSdrName(''); await load(); } catch (e) { setError(String(e)); } };
  const importCsv = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const data = new FormData(); data.append('file', file); setImportResult(''); try { const response = await fetch(`${apiBaseUrl}/api/leads/import`, { method: 'POST', body: data }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.message ?? 'Não foi possível importar o CSV'); setImportResult(`${result.imported} contatos importados${result.skipped ? ` · ${result.skipped} linhas ignoradas` : ''}`); event.target.value = ''; await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  const toggleDialer = async () => { try { await json(status.running ? '/api/dialer/pause' : '/api/dialer/start', { method: 'POST' }); await load(); } catch (e) { setError(String(e)); } };
  const showQr = async (id: string) => { if (qrBusy.current) return; qrBusy.current = true; setQrLoading(true); setQr({ qr_codes: [], status: 'loading', timeout_seconds: 60 }); setQrNumberId(id); try { setQr(await json(`/api/numbers/${id}/qr`)); setQrNumberId(id); } catch (e) { setError(String(e)); } finally { qrBusy.current = false; setQrLoading(false); } };
  const closeQr = () => { setQr(null); setQrNumberId(''); };
  const reconnectNumber = async (id: string) => { if (qrBusy.current) return; qrBusy.current = true; setQrLoading(true); setQr({ qr_codes: [], status: 'loading', timeout_seconds: 60 }); setQrNumberId(id); try { await json(`/api/numbers/${id}/reconnect`, { method: 'POST' }); await new Promise((resolve) => setTimeout(resolve, 5500)); setQr(await json(`/api/numbers/${id}/qr`)); setQrNumberId(id); } catch (e) { setError(String(e)); } finally { qrBusy.current = false; setQrLoading(false); } };
  const removeNumber = async (id: string, label: string) => { if (!window.confirm(`Remover o numero ${label}? A sessao sera desconectada e o registro local sera arquivado.`)) return; try { await json(`/api/numbers/${id}`, { method: 'DELETE' }); await load(); } catch (e) { setError(String(e)); } };
  const manualCall = async (id: string, name: string) => { if (!connected || !sdrReady) { setError('Conecte-se como SDR antes de iniciar uma ligação.'); return; } if (!available) { setError('Ative "Ficar disponível" antes de iniciar uma ligação.'); return; } if (!window.confirm(`Ligar agora para ${name}?`)) return; try { await json('/api/calls/manual', { method: 'POST', body: JSON.stringify({ leadId: id }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  const resetLead = async (id: string) => { if (!window.confirm('Resetar este contato? Nome e telefone serão mantidos, mas status e tentativas voltarão ao início.')) return; try { await json(`/api/leads/${id}/reset`, { method: 'POST' }); await load(); } catch (e) { setError(String(e)); } };
  const removeLead = async (id: string, name: string, phone: string) => { if (!window.confirm(`Remover o lead ${name || phone}? O contato e seu histórico de chamadas serão excluídos.`)) return; try { await json(`/api/leads/${id}`, { method: 'DELETE' }); await load(); } catch (e) { setError(String(e)); } };
  const clearLeads = async () => { if (!window.confirm('Limpar todos os contatos e o histórico de chamadas? Esta ação não pode ser desfeita.')) return; try { await json('/api/leads', { method: 'DELETE' }); await load(); } catch (e) { setError(String(e)); } };
  const navItems: { key: TabKey; label: string; icon: string }[] = [{ key: 'dashboard', label: 'Visão geral', icon: 'dashboard' }, { key: 'numbers', label: 'Números', icon: 'phone' }, { key: 'leads', label: 'Leads', icon: 'users' }, { key: 'sdrs', label: 'SDRs', icon: 'headset' }, { key: 'calls', label: 'Histórico', icon: 'history' }];
  const connectedNumbers = (status.numbers ?? []).filter((number: AnyRow) => ['connected', 'online', 'ready', 'authenticated'].includes(String(number.status).toLowerCase())).length; const moduleTitle = navItems.find((item) => item.key === tab)?.label ?? 'Visão geral';

  return <div className="app-shell">
    {showTrialBanner && <div className="trial-banner"><div className="banner-message"><button className="banner-close" onClick={() => setShowTrialBanner(false)} aria-label="Fechar aviso"><Icon name="close" size={15} /></button><span>O seu teste grátis vai expirar em breve. Atualize agora para manter todas as funcionalidades</span></div><Button variant="ghost" className="subscribe-button">Assinar agora</Button></div>}
    <div className="app-layout"><aside className="main-sidebar"><div className="brand"><div className="brand-mark"><Icon name="phone" size={17} /></div><div><strong>Zap<span>Call</span></strong><small>Operação SDR</small></div></div><div className="workspace-switcher"><span className="workspace-avatar">Z</span><div><strong>Minha operação</strong><small>Workspace local</small></div><Icon name="chevron" size={14} /></div><nav className="sidebar-nav" aria-label="Navegação principal"><span className="sidebar-label">Operação</span>{navItems.map((item) => <button key={item.key} className={`sidebar-item ${tab === item.key ? 'active' : ''}`} onClick={() => setTab(item.key)}><Icon name={item.icon} /><span>{item.label}</span>{item.key === 'calls' && calls.length > 0 && <em>{calls.length}</em>}</button>)}</nav></aside>
      <aside className="context-sidebar"><div className="context-title"><div className="context-icon"><Icon name="chart" size={16} /></div><div><strong>ZapCall</strong><small>Central de operação</small></div></div><span className="sidebar-label">Atalhos</span><button className={`context-link ${tab === 'dashboard' ? 'active' : ''}`} onClick={() => setTab('dashboard')}>Resumo da operação</button><button className={`context-link ${tab === 'leads' ? 'active' : ''}`} onClick={() => setTab('leads')}>Fila de contatos</button><button className={`context-link ${tab === 'calls' ? 'active' : ''}`} onClick={() => setTab('calls')}>Atividade recente</button><div className="context-status"><span className="status-line"><i className={status.running ? 'on' : ''}></i>Discador</span><Badge tone={status.running ? 'success' : 'neutral'}>{status.running ? 'Operando' : 'Pausado'}</Badge></div></aside>
      <main className="main-content"><div className="module-header"><div className="breadcrumb"><Icon name="chart" size={17} /><strong>{moduleTitle}</strong><span>/</span><span>Central de operação</span></div><div className="header-actions"><button className="date-filter"><Icon name="calendar" size={15} />29 jul 2026 – 27 ago 2026<Icon name="chevron" size={14} /></button><Button variant={status.running ? 'danger' : 'primary'} icon={status.running ? 'pause' : 'play'} onClick={() => void toggleDialer()}>{status.running ? 'Pausar discador' : 'Iniciar discador'}</Button></div></div>{activeCall?.mediaActive && <div className="answered-call-banner" role="status"><div className="answered-call-contact"><span className="answered-call-icon"><Icon name="phone" size={18} /></span><div><span>CLIENTE ATENDEU</span><strong>{activeCall.lead.name}</strong><small>{activeCall.lead.phone}</small></div></div><Button variant="danger" icon="close" onClick={hangup}>Encerrar chamada</Button></div>}{error && <div className="alert" role="alert"><Icon name="alert" size={17} /><span>{error}</span><button onClick={() => setError('')} aria-label="Fechar erro"><Icon name="close" size={16} /></button></div>}<div className="page-content">{tab === 'dashboard' && <Dashboard status={status} available={available} connected={connected} sdrReady={sdrReady} sdrs={sdrs} selectedSdr={selectedSdr} setSelectedSdr={setSelectedSdr} connectSdr={connectSdr} setAvailability={setAvailability} logs={logs} activeCall={activeCall} hangup={hangup} connectedNumbers={connectedNumbers} />}{tab === 'numbers' && <NumbersPage numbers={numbers} numberForm={numberForm} setNumberForm={setNumberForm} createNumber={createNumber} showQr={showQr} reconnectNumber={reconnectNumber} removeNumber={removeNumber} qrLoading={qrLoading} qr={qr} closeQr={closeQr} />}{tab === 'leads' && <LeadsPage leads={leads} leadForm={leadForm} setLeadForm={setLeadForm} createLead={createLead} importCsv={importCsv} importResult={importResult} clearLeads={clearLeads} manualCall={manualCall} resetLead={resetLead} removeLead={removeLead} />}{tab === 'sdrs' && <SdrsPage sdrs={sdrs} sdrName={sdrName} setSdrName={setSdrName} createSdr={createSdr} />}{tab === 'calls' && <CallsPage calls={calls} />}</div></main></div>
  </div>;
}
