import { FormEvent, useCallback, useEffect, useState } from 'react';
import { apiFetch, json } from '../../services/api';
import { Badge, Button, EmptyState, Panel, SectionHeader } from '../../components/ui';
import type { AnyRow } from '../../types';

const typeLabels: Record<string, string> = { correction: 'Correção', anonymization: 'Anonimização', deletion: 'Exclusão', export: 'Exportação' };
const statusLabels: Record<string, string> = { open: 'Aberta', processing: 'Processando', completed: 'Concluída', rejected: 'Rejeitada', cancelled: 'Cancelada' };

export function PrivacyPage() {
  const [phone, setPhone] = useState(''); const [subject, setSubject] = useState<AnyRow | null>(null); const [requests, setRequests] = useState<AnyRow[]>([]); const [requestType, setRequestType] = useState('export'); const [details, setDetails] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setRequests(await json('/api/privacy/requests')); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } }, []);
  useEffect(() => { void load(); }, [load]);
  const search = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { setSubject(await json(`/api/privacy/subjects/search?phone=${encodeURIComponent(phone)}`)); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } };
  const create = async () => { if (!subject?.phone) return; setBusy(true); try { await json('/api/privacy/requests', { method: 'POST', body: JSON.stringify({ phone: subject.phone, requestType, details: details.trim() || undefined }) }); setMessage('Solicitação registrada com prazo e trilha de auditoria.'); setDetails(''); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } };
  const process = async (id: string) => { if (!window.confirm('Processar esta solicitação agora? A anonimização/exclusão é irreversível para os dados identificáveis.')) return; try { await json(`/api/privacy/requests/${id}/process`, { method: 'POST' }); setMessage('Solicitação processada.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  const download = async (id: string) => { try { const response = await apiFetch(`/api/privacy/requests/${id}/export`); if (!response.ok) throw new Error('Exportação indisponível ou expirada'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `dados-titular-${id}.json`; anchor.click(); URL.revokeObjectURL(url); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  return <><div className="page-heading"><div><span className="eyebrow">LGPD</span><h1>Privacidade e dados</h1><p>Localize um titular, entenda os usos e processe solicitações com rastreabilidade.</p></div><Badge tone="info">{requests.filter((item) => ['open', 'processing'].includes(item.status)).length} em andamento</Badge></div>{message && <div className="alert" role="status"><span>{message}</span><button onClick={() => setMessage('')}>×</button></div>}<Panel><SectionHeader title="Buscar titular" description="A busca usa telefone exato e nunca atravessa empresas." /><form className="form-row" onSubmit={search}><input type="tel" required placeholder="Telefone com DDD" value={phone} onChange={(event) => setPhone(event.target.value)} /><Button icon="search" disabled={busy}>Buscar</Button></form>{subject && <div className="privacy-result"><div><strong>{subject.found ? 'Dados localizados' : 'Nenhum dado localizado'}</strong><small>{subject.phone} · usos: {(subject.uses ?? []).join(', ')}</small></div><div className="privacy-source-grid">{Object.entries(subject.sources ?? {}).map(([source, rows]) => <article key={source}><span>{source}</span><strong>{(rows as AnyRow[]).length}</strong><small>registro(s)</small></article>)}</div><div className="form-row"><select value={requestType} onChange={(event) => setRequestType(event.target.value)}>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input placeholder={requestType === 'correction' ? 'JSON: {"name":"Novo nome","phone":"..."}' : 'Detalhes opcionais'} value={details} onChange={(event) => setDetails(event.target.value)} /><Button type="button" onClick={() => void create()} disabled={busy}>Criar solicitação</Button></div></div>}</Panel><Panel><SectionHeader title="Solicitações de titulares" description="Exportações expiram após 24 horas; downloads e conclusões são auditados." /><div className="table-scroll"><table><thead><tr><th>Titular</th><th>Tipo</th><th>Estado</th><th>Prazo</th><th>Ações</th></tr></thead><tbody>{requests.map((item) => <tr key={item.id}><td>{item.subject_phone_masked}</td><td>{typeLabels[item.request_type]}</td><td><Badge tone={item.status === 'completed' ? 'success' : item.status === 'rejected' ? 'warning' : 'info'}>{statusLabels[item.status]}</Badge></td><td>{new Date(item.due_at).toLocaleDateString('pt-BR')}</td><td><div className="table-actions">{item.status === 'open' && <Button variant="ghost" onClick={() => void process(item.id)}>Processar</Button>}{item.status === 'completed' && item.request_type === 'export' && <Button variant="secondary" icon="download" onClick={() => void download(item.id)}>Baixar</Button>}</div></td></tr>)}</tbody></table>{!requests.length && <EmptyState title="Nenhuma solicitação" description="Novos pedidos aparecerão aqui." />}</div></Panel></>;
}
