import { useCallback, useEffect, useMemo, useState } from 'react';
import { Badge, Button, EmptyState, Panel, SectionHeader } from '../../components/ui';
import { json } from '../../services/api';
import type { AnyRow } from '../../types';

const activeStatuses = ['pending', 'due', 'reassigned'];
const statusLabel: Record<string, string> = { pending: 'Agendado', due: 'Vencido', reassigned: 'Reatribuído', completed: 'Concluído', cancelled: 'Cancelado', missed: 'Impedido' };
const groupFor = (item: AnyRow) => { const due = new Date(item.due_at); const now = new Date(); if (due.getTime() <= now.getTime()) return 'Atrasados'; if (due.toDateString() === now.toDateString()) return due.getTime() - now.getTime() < 60 * 60_000 ? 'Agora' : 'Hoje'; return 'Próximos'; };

export function CallbacksPage({ sdrs, isSdr }: { sdrs: AnyRow[]; isSdr: boolean }) {
  const [items, setItems] = useState<AnyRow[]>([]); const [status, setStatus] = useState(''); const [assignedSdrId, setAssignedSdrId] = useState(''); const [message, setMessage] = useState(''); const [selected, setSelected] = useState<string[]>([]);
  const load = useCallback(async () => { try { const params = new URLSearchParams(); if (status) params.set('status', status); if (assignedSdrId) params.set('assignedSdrId', assignedSdrId); setItems(await json(`/api/callbacks?${params}`)); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } }, [status, assignedSdrId]);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30_000); return () => clearInterval(timer); }, [load]);
  const groups = useMemo(() => ['Agora', 'Hoje', 'Próximos', 'Atrasados'].map((name) => ({ name, items: items.filter((item) => activeStatuses.includes(item.status) && groupFor(item) === name) })), [items]);
  const call = async (id: string) => { try { await json(`/api/callbacks/${id}/call`, { method: 'POST' }); setMessage('Chamada de retorno iniciada.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  const reschedule = async (item: AnyRow) => { const raw = window.prompt('Nova data e hora (AAAA-MM-DD HH:mm):', new Date(item.due_at).toLocaleString('sv-SE').slice(0, 16)); if (!raw) return; const due = new Date(raw.replace(' ', 'T')); try { await json(`/api/callbacks/${item.id}/reschedule`, { method: 'PATCH', body: JSON.stringify({ dueAt: due.toISOString() }) }); setMessage('Retorno reagendado.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  const cancel = async (item: AnyRow) => { const reason = window.prompt('Registre o impedimento ou motivo do cancelamento:'); if (!reason?.trim()) return; try { await json(`/api/callbacks/${item.id}/cancel`, { method: 'POST', body: JSON.stringify({ reason, status: 'missed' }) }); setMessage('Impedimento registrado.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  const reassign = async (ids: string[], sdrId?: string) => { try { await json('/api/callbacks/reassign', { method: 'PATCH', body: JSON.stringify({ callbackIds: ids, assignedSdrId: sdrId || undefined }) }); setSelected([]); setMessage(sdrId ? 'Retorno reatribuído.' : 'Retorno liberado para a equipe.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  const card = (item: AnyRow) => <article className={`callback-card${item.overdue ? ' overdue' : ''}`} key={item.id}>{!isSdr && <input type="checkbox" aria-label="Selecionar retorno" checked={selected.includes(item.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))} />}<div><strong>{item.lead_name}</strong><small>{item.lead_phone} · {new Date(item.due_at).toLocaleString('pt-BR')}</small>{item.notes && <p>{item.notes}</p>}</div><Badge tone={item.overdue ? 'warning' : 'info'}>{statusLabel[item.status] ?? item.status}</Badge><div className="table-actions"><Button variant="success" icon="phone" onClick={() => void call(item.id)}>Ligar</Button><Button variant="ghost" onClick={() => void reschedule(item)}>Reagendar</Button><Button variant="ghost" onClick={() => void cancel(item)}>Impedimento</Button>{!isSdr && <select aria-label="Responsável" value={item.assigned_sdr_id ?? ''} onChange={(event) => void reassign([item.id], event.target.value || undefined)}><option value="">Equipe</option>{sdrs.map((sdr) => <option key={sdr.id} value={sdr.id}>{sdr.name}</option>)}</select>}</div></article>;
  return <><div className="page-heading"><div><span className="eyebrow">AGENDA</span><h1>Retornos agendados</h1><p>{isSdr ? 'Seus retornos permanecem aqui até serem concluídos ou resolvidos.' : 'Agenda consolidada da equipe, com responsáveis e vencimentos.'}</p></div><Badge tone="warning">{items.filter((item) => item.overdue && activeStatuses.includes(item.status)).length} vencidos</Badge></div>{message && <div className="alert" role="status"><span>{message}</span><button onClick={() => setMessage('')}>×</button></div>}{!isSdr && <Panel><SectionHeader title="Filtros e ações em lote" action={selected.length ? <div className="panel-actions"><select defaultValue="" onChange={(event) => { if (event.target.value) void reassign(selected, event.target.value); }}><option value="">Reatribuir {selected.length} selecionados…</option>{sdrs.map((sdr) => <option key={sdr.id} value={sdr.id}>{sdr.name}</option>)}</select><Button variant="ghost" onClick={() => void reassign(selected)}>Liberar para equipe</Button></div> : undefined} /><div className="form-row"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos os estados</option>{Object.entries(statusLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><select value={assignedSdrId} onChange={(event) => setAssignedSdrId(event.target.value)}><option value="">Todos os SDRs</option>{sdrs.map((sdr) => <option key={sdr.id} value={sdr.id}>{sdr.name}</option>)}</select></div></Panel>}{groups.map((group) => <Panel key={group.name}><SectionHeader title={group.name} description={`${group.items.length} retorno(s)`} /><div className="callback-list">{group.items.map(card)}{!group.items.length && <EmptyState title={`Nenhum retorno em “${group.name.toLowerCase()}”`} />}</div></Panel>)}</>;
}
